### PR TITLE
Fix thread unsafe codec for UDP encode and decode

### LINKED ISSUE #144: Potential race condition in EncryptUDPConn
`ec.encoders` and `ec.decoders` might have concurrent map read/write if `AddCodec` and read/write are called concurrently

### PR DESCRIPTION
**Pull request by bufrr**
fix #144

### CODE REVIEW

File: udp.go [hunk 1]
```diff
@@ -134,29 +134,26 @@ func (ec *EncryptUDPConn) WriteMsgUDP(b, oob []byte, addr *net.UDPAddr) (n, oobn
 	ec.writeLock.Lock()
 	defer ec.writeLock.Unlock()
 
-	k := addr.String()
+	var k string
+	var msgLen int
+	ciphertext := make([]byte, MaxUDPBufferSize)
```
Comment (yilunzhang) [inline udp.go:139]: This can be a shared buffer

File: udp.go [hunk 2]
```diff
@@ -134,29 +134,26 @@ func (ec *EncryptUDPConn) WriteMsgUDP(b, oob []byte, addr *net.UDPAddr) (n, oobn
...
-		remoteAddr := ec.conn.RemoteAddr()
-		if k, ok := remoteAddr.(*net.UDPAddr); ok {
-			encoder = ec.encoders[k.String()]
-		}
-	}
-
-	var msgLen int
-	ciphertext := make([]byte, MaxUDPBufferSize)
-	if encoder != nil {
+		copy(ciphertext, b)
```
Comment (yilunzhang) [inline udp.go:148]: an easier approach without copy and msgLen: ciphertext = b

File: udp.go [hunk 3]
```diff
@@ -134,29 +134,26 @@ func (ec *EncryptUDPConn) WriteMsgUDP(b, oob []byte, addr *net.UDPAddr) (n, oobn
...
+		msgLen = len(b)
+	} else {
+		encoder := e.(*stream.Encoder)
```
Comment (yilunzhang) [inline udp.go:151]: an easier approach without msgLen: `ciphertext, err = ...`

File: udp.go [hunk 4]
```diff
@@ -123,48 +125,51 @@ func (ec *EncryptUDPConn) ReadFromUDPEncrypted(b []byte) (n int, addr *net.UDPAd
...
-		if k, ok := remoteAddr.(*net.UDPAddr); ok {
-			encoder = ec.encoders[k.String()]
-		}
-	}
-
-	var msgLen int
-	ciphertext := make([]byte, MaxUDPBufferSize)
-	if encoder != nil {
-		tmp, err := encoder.Encode(ciphertext, b)
+		ec.writeBuffer = b
```
Comment (yilunzhang) [inline udp.go:155]: Should copy

File: udp.go [hunk 5]
```diff
@@ -123,48 +125,51 @@ func (ec *EncryptUDPConn) ReadFromUDPEncrypted(b []byte) (n int, addr *net.UDPAd
...
+		encrypted = true
 		msgLen = len(tmp)
-	} else {
-		copy(ciphertext, b)
-		msgLen = len(b)
 	}
 
-	n, oobn, err = ec.conn.WriteMsgUDP(ciphertext[:msgLen], oob, addr)
-
+	n, oobn, err = ec.conn.WriteMsgUDP(ec.writeBuffer[:msgLen], oob, addr)
```
Comment (yilunzhang) [inline udp.go:167]: Probably a good idea to return `io.ErrShortWrite` if `n != msgLen`

**Review by yilunzhang — APPROVED** [review]
